apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/nati-cardoso-machado-gmail-com/teste89:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/nati-cardoso-machado-gmail-com/teste89:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: teste89
        chartPath: charts/teste89
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/nati-cardoso-machado-gmail-com/teste89"
          image.tag: "{{.DIGEST_HEX}}"
